name: ninja_asn1
description: Dart library that provides simple and elegant way to encode and decode ASN1
version: 2.0.0
homepage: https://github.com/ninja-dart/asn1

documentation:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.3
  ninja_hex: ^2.0.0
