name: ninja_asn1
description: Dart library that provides simple and elegant way to encode and decode ASN1
version: 1.0.0
homepage: https://github.com/ninja-dart/asn1

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  collection: ^1.14.12

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  ninja_hex: ^1.0.0
